// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SumRequest struct {
	Num1                 int32    `protobuf:"zigzag32,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2                 int32    `protobuf:"zigzag32,2,opt,name=num2,proto3" json:"num2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{0}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetNum1() int32 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *SumRequest) GetNum2() int32 {
	if m != nil {
		return m.Num2
	}
	return 0
}

type SumResponse struct {
	Result               int32    `protobuf:"zigzag32,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{1}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type CalculatePrimeNumberDecompositionRequest struct {
	Number               int32    `protobuf:"zigzag32,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatePrimeNumberDecompositionRequest) Reset() {
	*m = CalculatePrimeNumberDecompositionRequest{}
}
func (m *CalculatePrimeNumberDecompositionRequest) String() string { return proto.CompactTextString(m) }
func (*CalculatePrimeNumberDecompositionRequest) ProtoMessage()    {}
func (*CalculatePrimeNumberDecompositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{2}
}

func (m *CalculatePrimeNumberDecompositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatePrimeNumberDecompositionRequest.Unmarshal(m, b)
}
func (m *CalculatePrimeNumberDecompositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatePrimeNumberDecompositionRequest.Marshal(b, m, deterministic)
}
func (m *CalculatePrimeNumberDecompositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatePrimeNumberDecompositionRequest.Merge(m, src)
}
func (m *CalculatePrimeNumberDecompositionRequest) XXX_Size() int {
	return xxx_messageInfo_CalculatePrimeNumberDecompositionRequest.Size(m)
}
func (m *CalculatePrimeNumberDecompositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatePrimeNumberDecompositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatePrimeNumberDecompositionRequest proto.InternalMessageInfo

func (m *CalculatePrimeNumberDecompositionRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type CalculatePrimeNumberDecompositionResponse struct {
	PrimeNumber          int32    `protobuf:"zigzag32,1,opt,name=prime_number,json=primeNumber,proto3" json:"prime_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatePrimeNumberDecompositionResponse) Reset() {
	*m = CalculatePrimeNumberDecompositionResponse{}
}
func (m *CalculatePrimeNumberDecompositionResponse) String() string { return proto.CompactTextString(m) }
func (*CalculatePrimeNumberDecompositionResponse) ProtoMessage()    {}
func (*CalculatePrimeNumberDecompositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{3}
}

func (m *CalculatePrimeNumberDecompositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatePrimeNumberDecompositionResponse.Unmarshal(m, b)
}
func (m *CalculatePrimeNumberDecompositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatePrimeNumberDecompositionResponse.Marshal(b, m, deterministic)
}
func (m *CalculatePrimeNumberDecompositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatePrimeNumberDecompositionResponse.Merge(m, src)
}
func (m *CalculatePrimeNumberDecompositionResponse) XXX_Size() int {
	return xxx_messageInfo_CalculatePrimeNumberDecompositionResponse.Size(m)
}
func (m *CalculatePrimeNumberDecompositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatePrimeNumberDecompositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatePrimeNumberDecompositionResponse proto.InternalMessageInfo

func (m *CalculatePrimeNumberDecompositionResponse) GetPrimeNumber() int32 {
	if m != nil {
		return m.PrimeNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "calculator.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "calculator.SumResponse")
	proto.RegisterType((*CalculatePrimeNumberDecompositionRequest)(nil), "calculator.CalculatePrimeNumberDecompositionRequest")
	proto.RegisterType((*CalculatePrimeNumberDecompositionResponse)(nil), "calculator.CalculatePrimeNumberDecompositionResponse")
}

func init() {
	proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor_7f42938f8c8365cf)
}

var fileDescriptor_7f42938f8c8365cf = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x48, 0x4e, 0xcc, 0x49,
	0x2e, 0xcd, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x47, 0x30, 0x0b, 0x92, 0x90, 0x38, 0x7a, 0x05, 0x45,
	0xf9, 0x25, 0xf9, 0x42, 0x5c, 0x08, 0x11, 0x25, 0x13, 0x2e, 0xae, 0xe0, 0xd2, 0xdc, 0xa0, 0xd4,
	0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xd2, 0x5c, 0x43, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xc1, 0x20, 0x30, 0x1b, 0x2a, 0x66, 0x24, 0xc1, 0x04, 0x17, 0x33, 0x52, 0x52, 0xe5,
	0xe2, 0x06, 0xeb, 0x2a, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe3, 0x62, 0x2b, 0x4a, 0x2d,
	0x2e, 0xcd, 0x29, 0x81, 0x6a, 0x84, 0xf2, 0x94, 0x9c, 0xb8, 0x34, 0x9c, 0xa1, 0x56, 0xa5, 0x06,
	0x14, 0x65, 0xe6, 0xa6, 0xfa, 0x95, 0xe6, 0x26, 0xa5, 0x16, 0xb9, 0xa4, 0x26, 0xe7, 0xe7, 0x16,
	0xe4, 0x17, 0x67, 0x96, 0x64, 0xe6, 0xe7, 0xc1, 0xac, 0x16, 0xe3, 0x62, 0xcb, 0x03, 0xcb, 0xc2,
	0xcc, 0x80, 0xf0, 0x94, 0xfc, 0xb8, 0x34, 0x89, 0x30, 0x03, 0xea, 0x10, 0x45, 0x2e, 0x9e, 0x02,
	0x90, 0x9a, 0x78, 0x14, 0xa3, 0xb8, 0x0b, 0x10, 0xfa, 0x8c, 0x9e, 0x30, 0x72, 0x09, 0x3a, 0xc3,
	0xfd, 0x1f, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0x64, 0xc1, 0xc5, 0x1c, 0x5c, 0x9a, 0x2b,
	0x24, 0xa6, 0x87, 0x14, 0x58, 0x88, 0x70, 0x91, 0x12, 0xc7, 0x10, 0x87, 0x58, 0xa8, 0xc4, 0x20,
	0x34, 0x85, 0x91, 0x4b, 0x91, 0xa0, 0x03, 0x85, 0x4c, 0x90, 0x0d, 0x20, 0x36, 0x4c, 0xa4, 0x4c,
	0x49, 0xd4, 0x05, 0x73, 0x94, 0x01, 0xa3, 0x13, 0x5f, 0x14, 0x0f, 0x72, 0x22, 0x48, 0x62, 0x03,
	0x47, 0xbd, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x4d, 0x1b, 0x2e, 0x26, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	CalculatePrimeNumberDecomposition(ctx context.Context, in *CalculatePrimeNumberDecompositionRequest, opts ...grpc.CallOption) (CalculatorService_CalculatePrimeNumberDecompositionClient, error)
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) CalculatePrimeNumberDecomposition(ctx context.Context, in *CalculatePrimeNumberDecompositionRequest, opts ...grpc.CallOption) (CalculatorService_CalculatePrimeNumberDecompositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[0], "/calculator.CalculatorService/CalculatePrimeNumberDecomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceCalculatePrimeNumberDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_CalculatePrimeNumberDecompositionClient interface {
	Recv() (*CalculatePrimeNumberDecompositionResponse, error)
	grpc.ClientStream
}

type calculatorServiceCalculatePrimeNumberDecompositionClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceCalculatePrimeNumberDecompositionClient) Recv() (*CalculatePrimeNumberDecompositionResponse, error) {
	m := new(CalculatePrimeNumberDecompositionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	CalculatePrimeNumberDecomposition(*CalculatePrimeNumberDecompositionRequest, CalculatorService_CalculatePrimeNumberDecompositionServer) error
}

// UnimplementedCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (*UnimplementedCalculatorServiceServer) Sum(ctx context.Context, req *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (*UnimplementedCalculatorServiceServer) CalculatePrimeNumberDecomposition(req *CalculatePrimeNumberDecompositionRequest, srv CalculatorService_CalculatePrimeNumberDecompositionServer) error {
	return status.Errorf(codes.Unimplemented, "method CalculatePrimeNumberDecomposition not implemented")
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_CalculatePrimeNumberDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CalculatePrimeNumberDecompositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).CalculatePrimeNumberDecomposition(m, &calculatorServiceCalculatePrimeNumberDecompositionServer{stream})
}

type CalculatorService_CalculatePrimeNumberDecompositionServer interface {
	Send(*CalculatePrimeNumberDecompositionResponse) error
	grpc.ServerStream
}

type calculatorServiceCalculatePrimeNumberDecompositionServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceCalculatePrimeNumberDecompositionServer) Send(m *CalculatePrimeNumberDecompositionResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CalculatePrimeNumberDecomposition",
			Handler:       _CalculatorService_CalculatePrimeNumberDecomposition_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calculator/calculatorpb/calculator.proto",
}
